# 名字可以隨意，例如叫 Deploy React App
name: Deploy React App to Pages

on:
  push:
    branches: ["main"] # 💡 檢測當您推送代碼至主分支時觸發（若您的主分支叫 master 請改為 master）

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci # 💡 自動安裝 package.json 內鎖定的依賴項

      - name: Build Application
        run: npm run build # 💡 編譯出 dist 文件夾

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Build Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # 💡 告訴 GitHub 直接部署打包好的 dist 目錄

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
